description: >
  Regular expression visualizer using railroad diagrams
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - spec
baseurl: ""
url: "http://regexper.com"
markdown: kramdown
ga_account: "UA-37364632-1"
